version: '2.4'
services:

  seed:
    image: haghard/docker-cluster:0.3
    hostname: ${SEED_DNS}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 3072  #3 -cores
    environment:
      NODE_TYPE: seed
      SHARD: alpha
      DM: config

  alpha:
    image: haghard/docker-cluster:0.3
    environment:
      NODE_TYPE: shard
      SHARD: alpha
      DM: config
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - seed
    links:
     - "seed:${SEED_DNS}"

  betta:
    image: haghard/docker-cluster:0.3
    environment:
      NODE_TYPE: shard
      SHARD: betta
      DM: config
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - seed
    links:
      - "seed:${SEED_DNS}"

  gamma:
    image: haghard/docker-cluster:0.3
    environment:
      NODE_TYPE: shard
      SHARD: gamma
      DM: config
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - seed
    links:
      - "seed:${SEED_DNS}"


