version: '2.4'
services:

  master:
    image: haghard/docker-cluster:0.3
    hostname: ${MASTER_DNS}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 3072  #3 -cores
    environment:
      NODE_TYPE: master
      SHARD: alpha

  workerA:
    image: haghard/docker-cluster:0.3
    environment:
      NODE_TYPE: worker
      SHARD: alpha
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - master
    links:
     - "master:${MASTER_DNS}"

  workerB:
    image: haghard/docker-cluster:0.3
    environment:
      NODE_TYPE: worker
      SHARD: betta
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - master
    links:
      - "master:${MASTER_DNS}"

  workerG:
    image: haghard/docker-cluster:0.3
    environment:
      NODE_TYPE: worker
      SHARD: gamma
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - master
    links:
      - "master:${MASTER_DNS}"