version: '3.3'
services:

  seed:
    image: haghard/docker-cluster:0.2
    hostname: ${SEED_NODE}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SEED_JMX_PORT}:${SEED_JMX_PORT}"
    environment:
      node.type: seed

  worker:
    image: haghard/docker-cluster:0.2
    environment:
      node.type: worker
    depends_on:
      - seed
    links:
     - "seed:${SEED_NODE}"