version: '2.4'
services:

  master:
    image: haghard/docker-cluster:0.3
    hostname: ${MASTER_NODE}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SEED_JMX_PORT}:${SEED_JMX_PORT}"
    mem_limit: 300m
    mem_reservation: 100m
    environment:
      node.type: master

  worker:
    image: haghard/docker-cluster:0.3
    environment:
      node.type: worker
    depends_on:
      - master
    links:
     - "master:${MASTER_NODE}"