version: '2'

services:
  seed:
    image: "docker-compose-akka-cluster:0.1-SNAPSHOT"
    hostname: "seed-node"
    command: "-Dakka.remote.netty.tcp.hostname=seed-node"
    ports:
      - "9000:9000"
    environment:
      akka.remote.netty.tcp.hostname: seed-node
      akka.remote.netty.tcp.port: 2551
      akka.remote.netty.tcp.bind-hostname: seed-node
  node:
    image: "docker-compose-akka-cluster:0.1-SNAPSHOT"
    command: "-Dakka.remote.netty.tcp.port=2551"
    links: ["seed:seed-node"]


#command: "-Dakka.remote.netty.tcp.port=2551"
#command: "-Dakka.remote.netty.tcp.bind-hostname=seed-node"