#https://docs.docker.com/compose/compose-file/#resources
#https://github.com/chbatey/docker-jvm-akka/blob/master/docker-compose.yml
#http://www.batey.info/docker-jvm-k8s.html
#https://dzone.com/articles/docker-container-resource-management-cpu-ram-and-i

version: '2.4'
services:

  master:
    image: haghard/docker-cluster:0.3
    hostname: ${MASTER_DNS}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SEED_JMX_PORT}:${SEED_JMX_PORT}"
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 3072  #3 -cores
    environment:
      node.type: master
      role: alpha

  workerA:
    image: haghard/docker-cluster:0.3
    environment:
      node.type: worker
      role: alpha
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - master
    links:
     - "master:${MASTER_DNS}"

  workerB:
    image: haghard/docker-cluster:0.3
    environment:
      node.type: worker
      role: betta
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - master
    links:
      - "master:${MASTER_DNS}"

  workerG:
    image: haghard/docker-cluster:0.3
    environment:
      node.type: worker
      role: gamma
    mem_limit: 250m
    mem_reservation: 200m
    cpu_shares: 1048  #1 -core
    depends_on:
      - master
    links:
      - "master:${MASTER_DNS}"