version: '2'

services:

  seed:
    image: "docker-cluster:0.1-SNAPSHOT"
    hostname: ${SEED_NAME}
    ports:
      - "9000:9000"
    environment:
      akka.remote.netty.tcp.hostname: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}
        - "JVM_OPTS=-Xmx1g"

  node:
    image: "docker-cluster:0.1-SNAPSHOT"
    environment:
      akka.cluster.seed: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}
        - "JVM_OPTS=-Xmx1g"
    links: ["seed:${SEED_NAME}"]
    depends_on:
      - seed