version: '2'

services:

  seed:
    image: "docker-cluster:0.1-SNAPSHOT"
    hostname: "seed-node"
    ports:
      - "9000:9000"
    environment:
      akka.remote.netty.tcp.hostname: seed-node
      akka.remote.netty.tcp.port: 2551

  node:
    image: "docker-cluster:0.1-SNAPSHOT"
    environment:
      seed.tcp.hostname: seed-node
      akka.remote.netty.tcp.port: 2551
    links: ["seed:seed-node"]