version: '2'

services:

  seed:
    image: "docker-cluster:0.1-SNAPSHOT"
    hostname: ${SEED_NAME}
    ports:
      - "9000:9000"
    environment:
      akka.remote.netty.tcp.hostname: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}
        - "JVM_OPTS=-Xmx1g -Dcom.sun.management.jmxremote.port=1089 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=1089 -Dcom.sun.management.jmxremote=true"
  node:
    image: "docker-cluster:0.1-SNAPSHOT"
    environment:
      akka.cluster.seed: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}
      - "JVM_OPTS=-Xmx1g"
    links: ["seed:${SEED_NAME}"]
    depends_on:
      - seed