version: '2'

services:

  seed:
    image: "docker-cluster:0.1-SNAPSHOT"
    networks:
      - akka-cluster
    hostname: ${SEED_NAME}
    ports:
      - "9000:9000"
    environment:
      JVM_OPTS: "-d64 -server -XX:MaxGCPauseMillis=400 -XX:+UseStringDeduplication -Xmx1024m -XX:+UseG1GC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=2 \
      -Dcom.sun.management.jmxremote.port=1089 \
      -Dcom.sun.management.jmxremote.ssl=false \
      -Dcom.sun.management.jmxremote.authenticate=false \
      -Dcom.sun.management.jmxremote.local.only=false \
      -Dcom.sun.management.jmxremote.rmi.port=1089 \
      -Dcom.sun.management.jmxremote=true \
      -Djava.rmi.server.hostname="${SEED_NAME}
      "
      akka.remote.netty.tcp.hostname: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}

  node:
    image: "docker-cluster:0.1-SNAPSHOT"
    networks:
      - akka-cluster
    environment:
      akka.cluster.seed: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}
    links: ["seed:${SEED_NAME}"]
    depends_on:
      - seed