version: '2'

services:

  seed:
    image: "docker-cluster:0.1-SNAPSHOT"
    hostname: ${SEED_NAME}
    ports:
      - "9000:9000"
      - "1089:1089"
    environment:
      JAVA_OPTS: "-Ddatabase.url=xxx -Dcom.sun.management.jmxremote.port=1089 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=1089 -Dcom.sun.management.jmxremote=true -Djava.rmi.server.hostname=${HOST}"
      JVM_OPTS: "-Xmx1g -XX:+UseG1GC"
      akka.remote.netty.tcp.hostname: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}
  node:
    image: "docker-cluster:0.1-SNAPSHOT"
    environment:
      JVM_OPTS: "-Xmx1g -XX:+UseG1GC"
      akka.cluster.seed: ${SEED_NAME}
      akka.remote.netty.tcp.port: ${AKKA_PORT}
    links: ["seed:${SEED_NAME}"]
    depends_on:
      - seed