version: '2'

services:

  seed:
    image: "haghard/docker-cluster:0.2"
    hostname: ${SEED_NAME}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SEED_JMX_PORT}:${SEED_JMX_PORT}"
    environment:
      node.type: seed
    networks:
      dockernet:
        ipv4_address: 172.18.0.2

  worker:
    image: "haghard/docker-cluster:0.2"
    environment:
      node.type: worker
    links: ["seed:${SEED_NAME}"]
    depends_on:
      - seed

